### ISSUE TITLE
Q: is it possible to rollback to a previous version?

### ISSUE THREAD

**Issue by petre2dor** [Symbol-it/strapi-plugin-migrations#1]
My thinking here is that I want to run the same migration multiple times, at least in dev.

Thank you for your work :)

**Comment by TodepSymbol** [comment]
Hello @petre2dor ,

Sorry for the delay, you can not rollback your data but you can retry 1 or multiple migrations with the updateVersion method in the service migrations **strapi.plugins.migrations.services.migrations.updateVersion(oldversion)**

Thank you
